<nav class="p-8 pb-0 flex justify-between items-center max-w-4xl mx-auto">
    <a href="{{ route('home') }}" class="text-sky-600 hover:text-sky-700 dark:text-sky-400 dark:hover:text-sky-300 font-bold">
        &larr; Home
    </a>
    <div class="flex items-center space-x-4">
        <div class="text-gray-500 text-sm hidden sm:block">
            Generated by Resume Manager
        </div>
        <x-theme-toggle />
    </div>
</nav>
