<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $user->name }} - Resume</title>

    {{-- Vite Assets --}}
    @vite(['resources/css/resume.css'])

    {{-- Google Fonts: Space Mono --}}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <style>
        body {
            font-family: 'Space Mono', monospace;
        }
    </style>
</head>
<body class="antialiased dark:bg-gray-900 dark:text-white p-0">
    <div class="container mx-auto">
        <nav class="p-8 pb-0 flex justify-between items-center max-w-4xl mx-auto">
            <a href="{{ route('home') }}" class="text-sky-600 hover:text-sky-700 dark:text-sky-400 dark:hover:text-sky-300 font-bold">
                &larr; Home
            </a>
            <div class="text-gray-500 text-sm">
                Generated by Resume Manager
            </div>
        </nav>

        <main>
            {{ $resumeComponent }}
        </main>

        <footer class="py-6 border-t border-gray-200 dark:border-gray-800 text-center text-gray-500 text-xs max-w-4xl mx-auto">
            &copy; {{ date('Y') }} {{ $user->name }}. All rights reserved.
        </footer>
    </div>
</body>
</html>
